name: Node.js CI CD

on:
    push:
        branches: ['nestmain']
    pull_request:
        branches: ['nestmain']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.19.1]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Clean and Install Dependencies
              run: |
                  rm -rf node_modules package-lock.json
                  npm cache clean --force
                  npm install --legacy-peer-deps

            - name: Build Project
              run: npm run build

            - name: Run Tests
              run: npm test

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # 上传源代码到服务器（排除 node_modules）
            - name: Upload source code to server1
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: |
                      ./package.json
                      ./package-lock.json
                      ./tsconfig.build.json
                      ./nest-cli.json
                      ./tsconfig.json
                      ./.env.development
                      ./.env.production
                      ./src/
                      # 其他需要上传的文件或目录
                  target: /var/www/home1/ # 目标服务器路径

            # 在服务器上安装依赖并启动应用
            - name: Deploy to Alibaba Cloud Server (via SSH)
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /var/www/home1
                      npm install --legacy-peer-deps
                      npm run build
                      pm2 restart all || pm2 start npm --name "nest-app" -- run start:prod
